env:
  global:
    - DISPLAY=":99.0"
rvm:
  - 1.9.3
  - 2.0.0
  - ruby-head
matrix:
  allow_failures:
    - rvm: ruby-head
before_script:
  - ./travis-before-script.sh
  - sh -e /etc/init.d/xvfb start
after_script:
  - sh -e /ext/init.d/xvfb stop
